name: C/C++ CI

on:
  workflow_dispatch:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-20.04

    steps:
    - uses: actions/checkout@v2
    - name: make
      run: make
    - name: make install
      run: sudo make PREFIX=/usr/ install
    - name: test deps
      run: sudo apt-get install -y xvfb
    - name: smoke test build
      run: xvfb-run ./xst bash -c exit
    - name: smoke test install
      run: sync ; sleep 0.1 ; xvfb-run xst bash -c exit
